version: '3'

services:
  proxy:
    build:
      context: ./ops
      dockerfile: Dockerfile
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443


  app1:
    build:
      context: .
      dockerfile: Dockerfile
      target: app1
    command: prod

  app2:
    build:
      context: .
      dockerfile: Dockerfile
      target: app2
    command: prod