version: '3'

services:

  # TODO: make custom image with nginx.conf provided
  # and docker-compose push/pull it from docker hub
  proxy:
    image: nginx:1.23.2-alpine
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf


  app1:
    build:
      context: .
      dockerfile: Dockerfile
      target: app1
    command: prod

  app2:
    build:
      context: .
      dockerfile: Dockerfile
      target: app2
    command: prod