version: '3'

services:

  app1:
    build:
      context: .
      dockerfile: Dockerfile
      target: app1
    ports:
      - "9001:80"
    volumes:
      - ./app1:/code
    command: dev

  app2:
    build:
      context: .
      dockerfile: Dockerfile
      target: app2
    ports:
      - "9002:80"
    volumes:
      - ./app2:/code
    command: dev