version: '3'

services:
  proxy:
    image: nginx:1.23.2-alpine
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


  app1:
    image: wozniakpl/dev:app1
    ports:
      - "8001:80"

  app2:
    image: wozniakpl/dev:app2
    ports:
      - "8002:80"