name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push proxy
        uses: docker/build-push-action@v2
        with:
          context: ./ops
          file: ./ops/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dev:app-proxy
      - name: Build and push app1
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          target: app1
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dev:app1
      - name: Build and push app2
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          target: app2
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dev:app2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al